input:
  dir: "resources/input/"

# Paired-end config for cutadapt
cutadapt_pe:
  extra: "-q 20 --minimum-length 20"
  adapters: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"

bwa_mem:
  fasta: "/home/ro.d.bruijn/projects/sarah-satellites/RNA-satellite-snakemake-workflow/resources/references/dfam-fasta-download_satellites_primates_2024_11_05.fasta"
  
sambamba_sort:
  extra: ''
  threads: 30

samtools_merge:
  extra: ''
  threads: 30

multiqc:
  extra: ''

fastqc:
  extra: ''
 